name: united_natives
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.2
  wakelock_plus: ^1.2.7
  image_cropper: ^8.0.1
  firebase_core: ^3.3.0
  easy_localization: ^3.0.7
  percent_indicator: ^4.2.3
  flutter_staggered_grid_view: ^0.7.0
  random_string: ^2.3.1
  equatable: ^2.0.5
  flutter_tagging:
  scoped_model: ^2.0.0
  qr_flutter: ^4.1.0
  flutter_swiper_null_safety: ^1.0.2
  animations: ^2.0.11
  qr_code_scanner: ^1.0.1
  flutter_local_notifications: ^17.2.1+2
  fluttertoast: ^8.2.6
  flare_flutter: ^3.0.2
  rflutter_alert: ^2.0.7
  giffy_dialog: ^2.1.0
  rating_dialog: ^2.0.4
  flutter_mailer: ^2.1.2
  firebase_analytics: ^11.2.1
  firebase_messaging: ^15.0.4
  in_app_review: ^2.0.9
  cached_network_image: ^3.4.0
  flutter_bloc: ^8.1.6
  url_launcher: ^6.3.0
  flutter_signature_pad: ^3.0.1
  bloc: ^8.1.4
  share_plus: ^10.0.0
  dio: ^5.5.0+1
  shimmer: ^3.0.0
  pull_to_refresh: ^2.0.0
  flutter_slidable: ^3.1.1
  image_picker: ^1.1.2
  flutter_plugin_android_lifecycle: ^2.0.21
  google_maps_flutter: ^2.8.0
  photo_view: ^0.15.0
  intl: ^0.19.0
  intro_views_flutter: ^3.2.0
  font_awesome_flutter: ^10.7.0
  responsive_framework: ^0.2.0
  flutter_credit_card: ^4.0.1
  path_provider: ^2.1.4
  json_util: ^2.0.0
  chewie: ^1.8.3
  liquid_swipe: ^3.1.0
  introduction_screen:
  showcaseview: ^3.0.0
  flutter_secure_storage: ^9.2.2
  firebase_auth: ^5.1.4
  badges: ^3.1.2
  get: ^4.6.6
  date_format: ^2.0.7
  shared_preferences: ^2.3.1
  google_sign_in: ^6.2.1
  change_app_package_name: ^1.3.0
  email_validator: ^3.0.0
  device_info_platform_interface: ^2.0.1
  rxdart: ^0.28.0
  html: ^0.15.4
  http_auth: ^1.0.4
  permission_handler: ^11.3.1
  syncfusion_flutter_pdfviewer: ^26.2.8
  ndialog: ^4.3.1
  path: ^1.9.0
  syncfusion_flutter_datepicker: ^26.2.8
  provider: ^6.1.2
  file_picker: ^8.0.7
  firebase_crashlytics: ^4.0.4
  flutter_rounded_date_picker: ^3.0.4
  simple_animations: ^5.0.2
  flutter_spinkit: ^5.2.1
  flutter_svprogresshud: ^1.0.1
  google_mobile_ads: ^5.1.0
  package_info_plus: ^8.0.1
  flutter_colorpicker: ^1.1.0
  dotted_border: ^2.1.0
  webview_flutter: ^4.8.0
  device_info_plus: ^10.0.1
  timer_builder: ^2.0.0
  octo_image: ^2.1.0
  card_swiper: ^3.0.1
  location: ^7.0.0
  open_filex: ^4.4.0
  flutter_widget_from_html: ^0.15.1
  agora_rtc_engine: ^6.3.2
  flutter_keyboard_visibility:
  responsive_builder: ^0.7.1
  video_player: ^2.9.1
  flutter_launcher_icons: ^0.13.1
  rounded_loading_button_plus: ^3.0.1
  flutter_rating_bar: ^4.0.1
  sqflite: ^2.3.3+1
  syncfusion_flutter_charts: ^26.2.10


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/languages/
    - assets/images/intro_1.png
    - assets/images/intro_2.png
    - assets/images/intro_3.png
    - assets/images/myazlogo.png
    - assets/images/slide.png
    - assets/images/defaultProfile.png
    - assets/locale/

  fonts:
    - family: NunitoSans
      fonts:
        - asset: assets/fonts/NunitoSans-Light.ttf
          weight: 300
        - asset: assets/fonts/NunitoSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/NunitoSans-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/NunitoSans-Bold.ttf
          weight: 700
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Black.ttf
        - asset: assets/fonts/Raleway-BlackItalic.ttf
        - asset: assets/fonts/Raleway-Bold.ttf
        - asset: assets/fonts/Raleway-BoldItalic.ttf
        - asset: assets/fonts/Raleway-ExtraBold.ttf
        - asset: assets/fonts/Raleway-ExtraBoldItalic.ttf
        - asset: assets/fonts/Raleway-ExtraLight.ttf
        - asset: assets/fonts/Raleway-ExtraLightItalic.ttf
        - asset: assets/fonts/Raleway-Italic.ttf
        - asset: assets/fonts/Raleway-Light.ttf
        - asset: assets/fonts/Raleway-LightItalic.ttf
        - asset: assets/fonts/Raleway-Medium.ttf
        - asset: assets/fonts/Raleway-MediumItalic.ttf
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-SemiBold.ttf
        - asset: assets/fonts/Raleway-SemiBoldItalic.ttf
        - asset: assets/fonts/Raleway-Thin.ttf
        - asset: assets/fonts/Raleway-ThinItalic.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Black.ttf
        - asset: assets/fonts/Roboto-BlackItalic.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-BoldItalic.ttf
        - asset: assets/fonts/Roboto-Italic.ttf
        - asset: assets/fonts/Roboto-Light.ttf
        - asset: assets/fonts/Roboto-LightItalic.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto-MediumItalic.ttf
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Thin.ttf
        - asset: assets/fonts/Roboto-ThinItalic.ttf
    - family: Merriweather

      fonts:
        - asset: assets/fonts/Merriweather-Black.ttf
        - asset: assets/fonts/Merriweather-BlackItalic.ttf
        - asset: assets/fonts/Merriweather-Bold.ttf
        - asset: assets/fonts/Merriweather-BoldItalic.ttf
        - asset: assets/fonts/Merriweather-Italic.ttf
        - asset: assets/fonts/Merriweather-Light.ttf
        - asset: assets/fonts/Merriweather-LightItalic.ttf
        - asset: assets/fonts/Merriweather-Regular.ttf

