-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgKtcM6/OGGoUwteFr
BUSAAIqecqlx1FfeYhEyRGS70SKgCgYIKoZIzj0DAQehRANCAASfA8zI1bG8KPI3
A+ojL0t/ODNsVGf87F7eM+VGaMwWTm0LK4KsmYdzNDZHb924YHpaTzJkHNgdu9og
rlFKZ+0f
-----END PRIVATE KEY-----